exports.totalCols = 57
exports.leftCols = 16
exports.rightCols = 17
exports.frontCols = 12
exports.backCols = 12
exports.channels = 3
exports.totalRows = 2
exports.fps = 30
exports.totalChannels = exports.totalRows * exports.totalCols * exports.channels
exports.backendHost = 'http://localhost:8081'
